name: Generate index.m3u

on:
  push:
    paths:
      - 'streams/*.m3u'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate index.m3u
        run: |
          echo "#EXTM3U" > index.m3u
          for file in streams/*.m3u; do
            echo "" >> index.m3u
            echo "# ===== $(basename "$file") =====" >> index.m3u
            cat "$file" >> index.m3u
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.m3u
          git commit -m "Auto update index.m3u" || echo "No changes to commit"
          git push
